export default
{ "columns":0,
 "grid":
    {
     "height":1,
     "orientation":"orthogonal",
     "width":1
    },
 "margin":0,
 "name":"Items",
 "spacing":0,
 "tilecount":9,
 "tiledversion":"1.5.0",
 "tileheight":32,
 "tiles":[
        {
         "id":0,
         "image":"..\/Tiles\/Objects\/Jewels\/blue_crystal.base.111.png",
         "imageheight":32,
         "imagewidth":32,
         "properties":[
                {
                 "name":"Value",
                 "type":"int",
                 "value":4
                }, 
                {
                 "name":"Weight",
                 "type":"int",
                 "value":3
                }],
         "type":"Items"
        }, 
        {
         "id":1,
         "image":"..\/Tiles\/Objects\/Jewels\/diamond_exceptional.base.111.png",
         "imageheight":32,
         "imagewidth":32,
         "properties":[
                {
                 "name":"Value",
                 "type":"int",
                 "value":15
                }, 
                {
                 "name":"Weight",
                 "type":"int",
                 "value":4
                }],
         "type":"Items"
        }, 
        {
         "id":2,
         "image":"..\/Tiles\/Objects\/Jewels\/emerald.base.111.png",
         "imageheight":32,
         "imagewidth":32,
         "properties":[
                {
                 "name":"Value",
                 "type":"int",
                 "value":8
                }, 
                {
                 "name":"Weight",
                 "type":"int",
                 "value":5
                }],
         "type":"Items"
        }, 
        {
         "id":3,
         "image":"..\/Tiles\/Objects\/Jewels\/gem.clsc.111.png",
         "imageheight":32,
         "imagewidth":32,
         "properties":[
                {
                 "name":"Value",
                 "type":"int",
                 "value":6
                }, 
                {
                 "name":"Weight",
                 "type":"int",
                 "value":7
                }],
         "type":"Items"
        }, 
        {
         "id":4,
         "image":"..\/Tiles\/Objects\/Jewels\/goldcoin.base.111.png",
         "imageheight":32,
         "imagewidth":32,
         "type":"Items"
        }, 
        {
         "id":5,
         "image":"..\/Tiles\/Objects\/Jewels\/amethyst.base.111.png",
         "imageheight":32,
         "imagewidth":32,
         "properties":[
                {
                 "name":"Value",
                 "type":"int",
                 "value":10
                }, 
                {
                 "name":"Weight",
                 "type":"int",
                 "value":3
                }],
         "type":"Items"
        }, 
        {
         "id":6,
         "image":"..\/Tiles\/Objects\/Jewels\/amethyst_exceptional.base.111.png",
         "imageheight":32,
         "imagewidth":32,
         "type":"Items"
        }, 
        {
         "id":7,
         "image":"..\/..\/..\/crossfire-1.70.0.arch.tar\/weapon\/sword\/b_bsword_1.base.111.png",
         "imageheight":32,
         "imagewidth":32,
         "properties":[
                {
                 "name":"Currency",
                 "type":"bool",
                 "value":false
                }, 
                {
                 "name":"Value",
                 "type":"int",
                 "value":15
                }, 
                {
                 "name":"Weapon",
                 "type":"bool",
                 "value":true
                }, 
                {
                 "name":"Weight",
                 "type":"int",
                 "value":10
                }],
         "type":"Items"
        }, 
        {
         "id":8,
         "image":"..\/..\/..\/crossfire-1.70.0.arch.tar\/weapon\/sword\/b_dagger.base.111.png",
         "imageheight":32,
         "imagewidth":32,
         "properties":[
                {
                 "name":"Currency",
                 "type":"bool",
                 "value":false
                }, 
                {
                 "name":"Value",
                 "type":"int",
                 "value":10
                }, 
                {
                 "name":"Weapon",
                 "type":"bool",
                 "value":true
                }, 
                {
                 "name":"Weight",
                 "type":"int",
                 "value":6
                }],
         "type":"Items"
        }],
 "tilewidth":32,
 "type":"tileset",
 "version":1.5
}